Repository COS301-SE-2022/Team-Utilisation-Monitor, pull requests merged in 2022-05, with the labels that each got.

#21 Merge To Main
  README.md
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/apps/client/src/app/app-routing.module.ts
  team-utilisation-monitor/apps/client/src/app/app.component.html
  team-utilisation-monitor/libs/client/authentication/feature/.eslintrc.json
  team-utilisation-monitor/libs/client/authentication/feature/README.md
  team-utilisation-monitor/libs/client/authentication/feature/jest.config.ts
  team-utilisation-monitor/libs/client/authentication/feature/project.json
  team-utilisation-monitor/libs/client/authentication/feature/src/index.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/test-setup.ts
  team-utilisation-monitor/libs/client/authentication/feature/tsconfig.json
  team-utilisation-monitor/libs/client/authentication/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/client/authentication/feature/tsconfig.spec.json
  team-utilisation-monitor/libs/client/example/feature/.eslintrc.json
  team-utilisation-monitor/libs/client/example/feature/README.md
  team-utilisation-monitor/libs/client/example/feature/jest.config.ts
  team-utilisation-monitor/libs/client/example/feature/project.json
  team-utilisation-monitor/libs/client/example/feature/src/index.ts
  team-utilisation-monitor/libs/client/example/feature/src/lib/client-example-feature.module.ts
  team-utilisation-monitor/libs/client/example/feature/src/lib/edit-popup/edit-popup.component.html
  team-utilisation-monitor/libs/client/example/feature/src/lib/edit-popup/edit-popup.component.scss
  team-utilisation-monitor/libs/client/example/feature/src/lib/edit-popup/edit-popup.component.spec.ts
  team-utilisation-monitor/libs/client/example/feature/src/lib/edit-popup/edit-popup.component.ts
  team-utilisation-monitor/libs/client/example/feature/src/test-setup.ts
  team-utilisation-monitor/libs/client/example/feature/tsconfig.json
  team-utilisation-monitor/libs/client/example/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/client/example/feature/tsconfig.spec.json
  team-utilisation-monitor/tsconfig.base.json
Labels: front-end

#22 ✅ (backend)work: prisma,docker and the database
  team-utilisation-monitor/.env
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/apps/api/.eslintrc.json
  team-utilisation-monitor/apps/api/jest.config.ts
  team-utilisation-monitor/apps/api/project.json
  team-utilisation-monitor/apps/api/src/app/.gitkeep
  team-utilisation-monitor/apps/api/src/app/Authentication/Authentication.controller.ts
  team-utilisation-monitor/apps/api/src/app/Authentication/Authentication.module.ts
  team-utilisation-monitor/apps/api/src/app/Authentication/Authentication.service.ts
  team-utilisation-monitor/apps/api/src/app/Authentication/User.model.ts
  team-utilisation-monitor/apps/api/src/app/app.controller.spec.ts
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/apps/api/src/app/app.module.ts
  team-utilisation-monitor/apps/api/src/app/app.service.spec.ts
  team-utilisation-monitor/apps/api/src/app/app.service.ts
  team-utilisation-monitor/apps/api/src/assets/.gitkeep
  team-utilisation-monitor/apps/api/src/environments/environment.prod.ts
  team-utilisation-monitor/apps/api/src/environments/environment.ts
  team-utilisation-monitor/apps/api/src/main.ts
  team-utilisation-monitor/apps/api/tsconfig.app.json
  team-utilisation-monitor/apps/api/tsconfig.json
  team-utilisation-monitor/apps/api/tsconfig.spec.json
  team-utilisation-monitor/apps/client/src/app/app.component.html
  team-utilisation-monitor/doc/doc-filelist.js
  team-utilisation-monitor/doc/doc-script.js
  team-utilisation-monitor/doc/doc-style.css
  team-utilisation-monitor/docker-compose.yml
  team-utilisation-monitor/jest.preset.js
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.html
  team-utilisation-monitor/package.json
  team-utilisation-monitor/prisma/migrations/20220512134650_launch_1/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512144023_launch_2/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512145512_launch_3/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512161424_launch_4/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512162218_launch_5/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512181638_launch_reset/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512182550_launch_6/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512183741_launch_7/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512190724_launch_8/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512190927_launch_8/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512201639_launch_9/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512203907_launch_10/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512204703_launch_11/migration.sql
  team-utilisation-monitor/prisma/migrations/20220512211456_launch_12/migration.sql
  team-utilisation-monitor/prisma/migrations/migration_lock.toml
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
  team-utilisation-monitor/yarn.lock
Labels: backend, dev-ops

#23 Update Readme.md
  README.md
Labels: documentation

#31 Develop
  README.md
  team-utilisation-monitor/apps/client/src/app/app-routing.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/auth-routing.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end

#40 (databse) Updated our schema with new team entity
  team-utilisation-monitor/prisma/migrations/20220520205115_launch_13/migration.sql
  team-utilisation-monitor/prisma/migrations/20220520213743_launch_14/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: backend, database

#41 🚧 (backend) Added services,repository, api libs
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/apps/api/src/app/app.module.ts
  team-utilisation-monitor/libs/repository/data-access/.eslintrc.json
  team-utilisation-monitor/libs/repository/data-access/README.md
  team-utilisation-monitor/libs/repository/data-access/jest.config.ts
  team-utilisation-monitor/libs/repository/data-access/project.json
  team-utilisation-monitor/libs/repository/data-access/src/index.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.spec.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/repository-data-access.module.ts
  team-utilisation-monitor/libs/repository/data-access/tsconfig.json
  team-utilisation-monitor/libs/repository/data-access/tsconfig.lib.json
  team-utilisation-monitor/libs/repository/data-access/tsconfig.spec.json
  team-utilisation-monitor/libs/service/feature/.eslintrc.json
  team-utilisation-monitor/libs/service/feature/README.md
  team-utilisation-monitor/libs/service/feature/jest.config.ts
  team-utilisation-monitor/libs/service/feature/project.json
  team-utilisation-monitor/libs/service/feature/src/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.spec.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.spec.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/libs/service/feature/tsconfig.json
  team-utilisation-monitor/libs/service/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/service/feature/tsconfig.spec.json
  team-utilisation-monitor/tsconfig.base.json
Labels: backend, dev-ops

#42 🚧 (services) Added api layer to library
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/libs/api/feature/.eslintrc.json
  team-utilisation-monitor/libs/api/feature/README.md
  team-utilisation-monitor/libs/api/feature/jest.config.ts
  team-utilisation-monitor/libs/api/feature/project.json
  team-utilisation-monitor/libs/api/feature/src/index.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature.module.ts
  team-utilisation-monitor/libs/api/feature/tsconfig.json
  team-utilisation-monitor/libs/api/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/api/feature/tsconfig.spec.json
  team-utilisation-monitor/libs/api/shared/data-access/.eslintrc.json
  team-utilisation-monitor/libs/api/shared/data-access/README.md
  team-utilisation-monitor/libs/api/shared/data-access/jest.config.ts
  team-utilisation-monitor/libs/api/shared/data-access/project.json
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-shared-data-access.module.ts
  team-utilisation-monitor/libs/api/shared/data-access/tsconfig.json
  team-utilisation-monitor/libs/api/shared/data-access/tsconfig.lib.json
  team-utilisation-monitor/libs/api/shared/data-access/tsconfig.spec.json
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/tsconfig.base.json
Labels: backend, dev-ops, folder(s) and files

#43 🚧 (Api)Added resolver.ts file
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.spec.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
Labels: backend, dev-ops, folder(s) and files

#44 🚧 (API)Created user-person entity
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
Labels: backend, dev-ops, folder(s) and files, api

#45 (repository)Changed RepositoryDataAccessModule
  team-utilisation-monitor/libs/repository/data-access/src/lib/repository-data-access.module.ts
Labels: backend, dev-ops, folder(s) and files, api

#46 🚧 (prismaService) Added a prisma service
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/.eslintrc.json
  team-utilisation-monitor/libs/shared/services/prisma-services/README.md
  team-utilisation-monitor/libs/shared/services/prisma-services/jest.config.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/project.json
  team-utilisation-monitor/libs/shared/services/prisma-services/src/index.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/shared-services-prisma-services.module.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/shared-services-prisma-services.service.spec.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/shared-services-prisma-services.service.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/tsconfig.json
  team-utilisation-monitor/libs/shared/services/prisma-services/tsconfig.lib.json
  team-utilisation-monitor/libs/shared/services/prisma-services/tsconfig.spec.json
  team-utilisation-monitor/tsconfig.base.json
Labels: backend, dev-ops, folder(s) and files, api

#49 Rourke
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature.module.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: backend, api

#50 🚧 (CQRS) created the first query files
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-person.query.ts
Labels: backend, folder(s) and files, api

#51 🚀 (services) First Query working!
  team-utilisation-monitor/libs/repository/data-access/src/index.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-persons.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-persons.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-person.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/shared-services-prisma-services.module.ts
Labels: backend, database, folder(s) and files, api

#52 🚧 (repository)getAllUserPerson service running
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, api

#55 🚧(services) Added a getOnePerson query and handler
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-one-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-one-person.query.ts
Labels: backend, api

#56 🚧(services) get-one-person.query is working
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-one-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-one-person.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, folder(s) and files, services

#57 🚧 (service)Created a Login Query(Untested)
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/login.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/login.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, folder(s) and files, services, feature untested

#58 🚧 (api) api layer is complete
  team-utilisation-monitor/apps/api/src/app/app.module.ts
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: backend, folder(s) and files, api

#60 Installed Angular Material
  node_modules/.yarn-integrity
  team-utilisation-monitor/apps/api/project.json
  team-utilisation-monitor/apps/client-e2e/project.json
  team-utilisation-monitor/apps/client/project.json
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/apps/client/src/index.html
  team-utilisation-monitor/apps/client/src/styles.scss
  team-utilisation-monitor/libs/api/feature/project.json
  team-utilisation-monitor/libs/api/shared/data-access/project.json
  team-utilisation-monitor/libs/client/authentication/feature/project.json
  team-utilisation-monitor/libs/client/example/feature/project.json
  team-utilisation-monitor/libs/client/signup-as-company/feature/project.json
  team-utilisation-monitor/libs/client/signup-as-individual/feature/project.json
  team-utilisation-monitor/libs/client/signup-as-team/feature/project.json
  team-utilisation-monitor/libs/repository/data-access/project.json
  team-utilisation-monitor/libs/service/feature/project.json
  team-utilisation-monitor/libs/shared/services/prisma-services/project.json
  team-utilisation-monitor/nx.json
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
  yarn.lock
Labels: front-end

#62 Remove node_modules
  node_modules/.yarn-integrity
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
Labels: front-end

#66 Fixed a conflict issue!
  team-utilisation-monitor/apps/api/src/main.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: bug, backend, api

#67 Fixed The api graphql
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: bug, backend, api

#69 Login Page integrated w/ Angular Material
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
Labels: front-end

#71 Finalize Login Page
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
Labels: front-end

#73 🚀 (marrige)first marriage front and backend
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/auth-routing.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-service/client-authentication-service.service.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-service/client-authentication-service.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.ts
  team-utilisation-monitor/nx.json
  team-utilisation-monitor/package.json
Labels: front-end, backend, folder(s) and files, api

#75 Login Page form and styling update
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
Labels: front-end

#76 🚧 (services)Created commands to create person
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-person.command.ts
Labels: backend, folder(s) and files, api

#83 Gift
  team-utilisation-monitor/apps/api/src/app/Authentication/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/auth-routing.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.scss
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end, api

#84 Sign-up service is up and running
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-company.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-person.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, services

#85 🚀 (sign-up)signup functionality is done front-end
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-service/client-authentication-service.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/example/example.component.ts
Labels: front-end, backend, api, services

#87 adHome added buttons to nav's
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/home-page/home-page.component.ts
Labels: front-end

#91 🐛 deleted some files
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/libs/client/admin/feature/.eslintrc.json
  team-utilisation-monitor/libs/client/admin/feature/README.md
  team-utilisation-monitor/libs/client/admin/feature/jest.config.ts
  team-utilisation-monitor/libs/client/admin/feature/project.json
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/test-setup.ts
  team-utilisation-monitor/libs/client/admin/feature/tsconfig.json
  team-utilisation-monitor/libs/client/admin/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/client/admin/feature/tsconfig.spec.json
  team-utilisation-monitor/tsconfig.base.json
Labels: bug, fixed a bug

#105 Updated Admin Front End
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.scss
Labels: front-end

#112 🚧 (database)Added invites field to the database
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/migrations/20220528012141_launch_15/migration.sql
  team-utilisation-monitor/prisma/migrations/20220528125835_launch_16/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: database, api, services

#113 🐛 (services)Finally fixed the login function!!
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: api, services

#114 🚧 (database) Added utilization to the database
  team-utilisation-monitor/prisma/migrations/20220528181235_launch_17/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#117 Front End of Admin Company View and NavBar component implementation
  node_modules/.yarn-integrity
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-owner-individual/comp-owner-individual.component.ts
Labels: front-end

#123 Finishing up Company View Front End
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
Labels: front-end

#125 Gift
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/apps/client/src/app/app-routing.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/shared/feature/.eslintrc.json
  team-utilisation-monitor/libs/client/shared/feature/README.md
  team-utilisation-monitor/libs/client/shared/feature/jest.config.ts
  team-utilisation-monitor/libs/client/shared/feature/project.json
  team-utilisation-monitor/libs/client/shared/feature/src/index.ts
  team-utilisation-monitor/libs/client/shared/feature/src/lib/client-shared-feature.module.ts
  team-utilisation-monitor/libs/client/shared/feature/src/lib/navbar/navbar.component.html
  team-utilisation-monitor/libs/client/shared/feature/src/lib/navbar/navbar.component.scss
  team-utilisation-monitor/libs/client/shared/feature/src/lib/navbar/navbar.component.spec.ts
  team-utilisation-monitor/libs/client/shared/feature/src/lib/navbar/navbar.component.ts
  team-utilisation-monitor/libs/client/shared/feature/src/lib/shared-routing.module.ts
  team-utilisation-monitor/libs/client/shared/feature/src/test-setup.ts
  team-utilisation-monitor/libs/client/shared/feature/tsconfig.json
  team-utilisation-monitor/libs/client/shared/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/client/shared/feature/tsconfig.spec.json
  team-utilisation-monitor/tsconfig.base.json
Labels: front-end, fixed a bug
