Repository COS301-SE-2022/Team-Utilisation-Monitor, pull requests merged in 2022-09, with the labels that each got.

#523 Develop
  team-utilisation-monitor/Microservice-Authentication/.env
  team-utilisation-monitor/Microservice-Authentication/Dockerfile
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/prisma/schema.prisma
  team-utilisation-monitor/Microservice-Authentication/src/main.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-skill.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-skill.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/skills.state.ts
Labels: bug, backend, Fix

#525 🐛 (Fix)Fixed the addSkills issue
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/skills.state.ts
Labels: Fix, NGSX

#528 forgotten responsive updates
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
Labels: front-end

#526 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: front-end, backend, fixed a bug

#530 Merge to Cornel
  README.md
  team-utilisation-monitor/Microservice-Authentication/.env
  team-utilisation-monitor/Microservice-Authentication/Dockerfile
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/prisma/schema.prisma
  team-utilisation-monitor/Microservice-Authentication/src/main.ts
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-skill.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-skill.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-skill.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/skills.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/team.state.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: front-end

#531 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
Labels: Fix

#533 Gift
  team-utilisation-monitor/Microservice-Authentication/prisma/seed.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/migrations/20220914004304_launch_41/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database, services

#536 (AWS) Apis offically Live
  team-utilisation-monitor/.dockerignore
  team-utilisation-monitor/.env
  team-utilisation-monitor/Microservice-Authentication/.dockerignore
  team-utilisation-monitor/Microservice-Authentication/docker-compose.yml
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/shared/Entities/api-auth-admin.entity.ts
  team-utilisation-monitor/Microservice-Authentication/src/main.ts
  team-utilisation-monitor/api.Dockerfile
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: database, api, MicroServices

#538 Revert "(AWS) Apis offically Live"
  team-utilisation-monitor/.dockerignore
  team-utilisation-monitor/.env
  team-utilisation-monitor/Microservice-Authentication/.dockerignore
  team-utilisation-monitor/Microservice-Authentication/docker-compose.yml
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/shared/Entities/api-auth-admin.entity.ts
  team-utilisation-monitor/Microservice-Authentication/src/main.ts
  team-utilisation-monitor/api.Dockerfile
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: dev-ops

#539 (microservices) Microservices is now running on localhost
  team-utilisation-monitor/Microservice-Authentication/.env
Labels: api, MicroServices

#540 (FrontEnd)Refinement to the login and registration forms
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/shared/Entities/api-auth-admin.entity.ts
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/index.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/classes-error-strings.ts
Labels: front-end, api

#541 🚧 (Backend)The system can now handle multiple admins
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
Labels: api, services

#542 🚧 (ngxs)Complete project-file setup done
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-closed-projects.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-numer-of-closed-projects.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-closed-projects.state.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: NGSX

#543 🐛 (Fix) Was not increasing the number of completed projects
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-company-stats.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-closed-projects.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-numer-of-closed-projects.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-closed-projects.state.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: NGSX

#544 (FrontEnd) Complete Projects Now working.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: services

#545 🚧 (services)Added getAllTeamsOfACompnay cqrs
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-team.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-Teams-Of-A-Company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-teams-of-company.query.ts
Labels: api, services

#547 (ngxs) Setup for team members done
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-team.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-team-member.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-team-member.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-team-member.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/team-members.state.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-Teams-Of-A-Company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/classes-error-strings.ts
Labels: backend, NGSX

#548 Develop
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-reset-add-team-member.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
Labels: NGSX

#550 🚧 (ngxs) Setup ready for Company View
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-employee.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-employee.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-employees.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/employees.state.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: NGSX

#551 🚧 (Fixed) A bug regarding the add skills
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
Labels: Fix, NGSX

#552 🚧 (ngxs)Remove skills working
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/UpdateUserSkill.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/remove-skills.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/remove-skill.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: NGSX

#558 🚧 (Front End)Fixed the login logic
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: backend

#560 Gift
  team-utilisation-monitor/.vscode/settings.json
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/DeleteTeam.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/DeleteTeam.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetRecomendedTeam.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetRecomendedTeam.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220918193319_cornel_migration/migration.sql
  team-utilisation-monitor/prisma/migrations/20220920143022_launch_42/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: backend, database, api

#562 front-end updates from branch 'theo-sprint4'
  .DS_Store
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end

#567 🚧 (Microservices)Microservices is fixed
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
Labels: backend

#572 🐛 (Fix)Creating a user where the invite code doesn't exist
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
Labels: MicroServices

#580 Gift
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, api

#581 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-position.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/AddPosition.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/AddPosition.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/index.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/classes-error-strings.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/message-object.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/positions-factory/creator.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/positions-factory/position-creator.ts
  team-utilisation-monitor/prisma/migrations/20220921201941_launch_43/migration.sql
  team-utilisation-monitor/prisma/migrations/20220921215709_launch_44/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: services

#583 🚧 (services) getAllPositions() and createPositions is working
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-position.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/AddPosition.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-positions-of-company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-positions-of-company.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/index.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/classes-error-strings.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/positions-factory/creator.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/positions-factory/position-creator.ts
Labels: services

#584 🐛 (fix) null error in the PositionEntity
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-position.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
Labels: Fix

#585 🚧 (FrontEnd)The addPosition is now working
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
Labels: front-end, services

#587 🚧 (Service) AssignPositions to users working
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-position-to-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-position-to-user.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-positions-of-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-positions-of-user.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: api, services

#588 update
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-position.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-team-member.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/AddPosition.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-position-to-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/AddPosition.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-position-to-user.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-positions-of-company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-positions-of-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-positions-of-company.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-positions-of-user.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/index.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/classes-error-strings.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/classes/message-object.ts
  team-utilisation-monitor/prisma/migrations/20220921201941_launch_43/migration.sql
  team-utilisation-monitor/prisma/migrations/20220921215709_launch_44/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, api, Deployment

#590 explore
  team-utilisation-monitor/.env
  team-utilisation-monitor/docker-compose.yml
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end, backend

#592 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-position.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.spec.ts
Labels: api, services

#593 🚧 (FrontEnd)Replaced the getCompany with getAllPersons
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
Labels: services

#591 Create Completed Project Component
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.ts
Labels: front-end

#595 🚧 (database) added migration to the position schema
  team-utilisation-monitor/.env
  team-utilisation-monitor/docker-compose.yml
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-position-to-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-position-to-user.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220923002856_launch_45/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#596 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: services

#599 Front end modifications on the create Project popup
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
Labels: front-end, fixed a bug

#601 update
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end, backend, api, Deployment

#602 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/remove-position.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/remove-position.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end

#603 🚧 (frontEnd)ngxs for positions is working
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-position.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-position.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-positions.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/positions.state.ts
Labels: NGSX

#604 🚧 (ngxs) Working for Completed Projects
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-complete-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-complete-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/completed-projects.state.ts
Labels: front-end, NGSX

#605 update
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-complete-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-position.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-complete-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-position.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-positions-popup/comp-add-positions-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-positions.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/completed-projects.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/positions.state.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/remove-position.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/remove-position.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: api

#606 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
Labels: backend, api, Done

#607 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
Labels: Fix, NGSX

#608 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end, backend

#609 update
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-completed-projects-list/comp-completed-projects-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end

#610 Theo sprint4
  team-utilisation-monitor/.env
  team-utilisation-monitor/docker-compose.yml
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-trend-skill.entity.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-trend-skill.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-trend-skill.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end

#613 Responsiveness: AdminHomePage
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
Labels: front-end

#615 Responsiveness: AdminListView
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.scss
Labels: front-end

#617 Gift
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/DeleteTeam.handler.ts
Labels: front-end, backend, api

#619 Responsiveness: TeamProjectView
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.scss
Labels: front-end

#622 API populations and styling
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end

#625 skill recommendation level justification
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: api

#627 fixed sonarclous error -"title duplicate first used in line 43
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
Labels: api

#624 🐛 (Fix) Team-project view contructor error
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
Labels: Fix

#628 (Fix) URI for main db changed
  team-utilisation-monitor/.env
Labels: Fix

#629 (Tags) Added helper tages to the URI Files
  team-utilisation-monitor/.env
  team-utilisation-monitor/Microservice-Authentication/.env
Labels: Fix

#632 update
  README.md
  team-utilisation-monitor/.env
  team-utilisation-monitor/Microservice-Authentication/.env
  team-utilisation-monitor/apps/client-e2e/src/integration/app.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
Labels: api

#634 🐛 (Fix) Update main
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end, Fix

#635 Added Dockerfile and api.Dockerfile
  team-utilisation-monitor/Dockerfile
  team-utilisation-monitor/api.Dockerfile
  team-utilisation-monitor/nginx/nginx.conf
Labels: Fix
