Repository COS301-SE-2022/Team-Utilisation-Monitor, pull requests merged in 2022-06, with the labels that each got.

#127 Front End Admin Home Page and navbars
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-admin-topnav/comp-admin-topnav.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
Labels: enhancement, front-end

#121 Develop
  .idea/.gitignore
  .idea/Team-Utilisation-Monitor.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/apps/client/src/app/app-routing.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/auth-routing.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/client-authentication-feature.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-team/signup-as-team.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup/signup.component.ts
  team-utilisation-monitor/libs/client/individual/feature/.eslintrc.json
  team-utilisation-monitor/libs/client/individual/feature/README.md
  team-utilisation-monitor/libs/client/individual/feature/jest.config.ts
  team-utilisation-monitor/libs/client/individual/feature/project.json
  team-utilisation-monitor/libs/client/individual/feature/src/index.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/test-setup.ts
  team-utilisation-monitor/libs/client/individual/feature/tsconfig.json
  team-utilisation-monitor/libs/client/individual/feature/tsconfig.lib.json
  team-utilisation-monitor/libs/client/individual/feature/tsconfig.spec.json
  team-utilisation-monitor/tsconfig.base.json
Labels: front-end, fixed a bug

#137 Updated all admin pages and sideNav
  team-utilisation-monitor/angular.json
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
Labels: front-end

#144 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-invite-code.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-invite-code.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-company.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-invite-code.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/yarn.lock
Labels: backend, api, services, repository

#145 🚧 (services) createTeam and createObject are live
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-project.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-team.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-project.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-team.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-project.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-team.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, api, services

#148 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-admin.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-admin.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-user.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/prisma/migrations/20220607182117_launch_19/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/yarn.lock
Labels: backend, api, services, repository

#149 🚧 (services) getPendingRequests is up an running
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-pending-requests.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-pending-requests.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api, services, repository

#150 🚧 (services) fixed a bug regarding the createUser service
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-user-id.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api, repository

#151 🚧 (services) approve Requests is working
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/approve-request.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/approve-request.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api

#152 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: enhancement, backend

#153 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-company-stats.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-company-stats.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-company-stats.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api, services

#154 🚧 (services) getAllEmployees() is working
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-employees-of-company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-employees-of-company.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api

#157 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: enhancement, backend, dev-ops, api

#159 Added Popups to Navbar
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
Labels: front-end

#160 Develop
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/ind-routing.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: backend, api

#161 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: backend, api

#165 Develop
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/ind-routing.module.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, api, services

#167 Hotfix footers in Login/Signup Pages
  team-utilisation-monitor/apps/client/src/app/app-routing.module.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/index.ts
Labels: front-end, fixed a bug

#171 Finalized Side Nav Popups
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.scss
Labels: front-end

#172 Develop
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, test

#176 Added Done button To Project View
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.scss
Labels: front-end

#177 Develop
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-user.handler.ts
Labels: backend, api

#179 🚧(front-end)- non-navigating individual profile and home page
  team-utilisation-monitor/apps/client/src/app/app-routing.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-project.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-team.entity.ts
  team-utilisation-monitor/libs/client/individual/feature/src/index.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/ind-routing.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-project-or-teams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-projects-or-teams.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end, services, in progress

#181 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/approve-request-v-email.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/approve-request-v-email.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-project-or-teams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, database, api, repository

#184 Develop
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: front-end

#187 Hotfix: moved team name to another backend linking
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
Labels: bug, front-end, backend

#189 🐛
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, api
