Repository COS301-SE-2022/Team-Utilisation-Monitor, pull requests merged in 2022-07, with the labels that each got.

#194 Develop
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: bug, fixed a bug

#200 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/approve-request-v-email.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/approve-request.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/approve-request.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end, backend, api

#209 🚧(front-end)- card styling, monthly utilisation, hours line graph
  .idea/misc.xml
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/ind-routing.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end, database, Done

#210 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/getCompany.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/getInviteCode.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/getInviteCode.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end, backend, api, fixed a bug

#212 Gift
  team-utilisation-monitor/NX
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/utilization-graph/utilization-graph.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/utilization-graph/utilization-graph.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/utilization-graph/utilization-graph.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/utilization-graph/utilization-graph.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/weekly-utilisation-graph/weekly-utilisation-graph.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/weekly-utilisation-graph/weekly-utilisation-graph.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/weekly-utilisation-graph/weekly-utilisation-graph.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/weekly-utilisation-graph/weekly-utilisation-graph.component.ts
Labels: front-end, api

#220 (front-end): individual utilisation graph and nav done
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/ind-routing.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
Labels: front-end, Done

#221 🚧 (microservices) RegisterUser is working on the mico
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/libs/auth-resolver/src/authentication-resolvers.resolver.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/handlers/index.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/handlers/register-user.hanlder.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/impl/register-user.command.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/services.service.ts
Labels: backend, api, services, MicroServices

#222 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/addTeamMember.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/addTeamMember.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: enhancement, backend, api

#223 🚧 (Microservice) Login Function Working
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/libs/auth-resolver/src/authentication-resolvers.resolver.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/queries/handlers/index.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/queries/handlers/loginHandler.handler.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/queries/impl/login.query.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/services.module.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/services.service.ts
Labels: database, services, MicroServices

#230 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/getTeamMembers.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/getTeamMembers.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end, backend, api

#233 develop
  team-utilisation-monitor/Microservice-Authentication/.dockerignore
  team-utilisation-monitor/Microservice-Authentication/Dockerfile
  team-utilisation-monitor/Microservice-Authentication/docker-compose.yml
  team-utilisation-monitor/Microservice-Authentication/prisma/schema.prisma
  team-utilisation-monitor/Microservice-Authentication/src/main.ts
Labels: services, MicroServices

#237 🚧 (Database) Revision of Schema of main DB(v5)
  team-utilisation-monitor/Microservice-Authentication/prisma/schema.prisma
  team-utilisation-monitor/prisma/schema.prisma
Labels: database, services

#242 Develop
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/handlers/register-user.hanlder.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
Labels: front-end, api

#243 🚧 (Microservices) Removed a misleading comment
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/handlers/register-user.hanlder.ts
Labels: MicroServices

#244 🚧 working on intergrating front and backend.
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-admin.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-admin.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end

#245 🚧 (microservices)Changed the resolvers for the new registration
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/login.handler.ts
Labels: test, api, MicroServices

#246 🚀 (Microservices)RegisterAdmin is working on microservice.
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-person.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-project.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-person.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: api, services, MicroServices

#248 🚀 (Microservices)RegisterUser is working on microservice.
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-user.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/create-user.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: api, MicroServices

#249 🚀 (Microservices)Login Working!!!!!
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: services, MicroServices

#250 🩹 (front-end)Fixed an issue regarding Admin page
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: front-end, api, MicroServices

#251 🚧 (Frontend) Users who where not approved could sign up- fixed
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end, database, api

#252 Added bar chart to Admin Home
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-routing.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.ts
Labels: front-end

#255 🚧 (FrontEnd)Done linking the individual page
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end

#256 🚧 (Microservices) Microservices is now stable
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/libs/auth-resolver/src/authentication-resolvers.resolver.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/handlers/register-admin.handler.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/handlers/register-user.hanlder.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/impl/register-admin.command.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/commands/impl/register-user.command.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/services.service.ts
  team-utilisation-monitor/Microservice-Authentication/prisma/schema.prisma
  team-utilisation-monitor/Microservice-Authentication/shared/Entities/api-auth-admin.entity.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
Labels: front-end, backend, MicroServices

#257 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/DeleteEmployee.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/DeleteTeamMember.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/create-admin.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/DeleteEmployee.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/DeleteTeamMember.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api

#259 🚑 (Microservices) .env file was in .gitignore
  team-utilisation-monitor/Microservice-Authentication/.env
  team-utilisation-monitor/Microservice-Authentication/.gitignore
Labels: services, MicroServices

#261 🚧 (MicroServices)I am giving my node modeules.
  team-utilisation-monitor/Microservice-Authentication/.gitignore
Labels: MicroServices

#262 🩹 (Frontend) Updated the linking. Was not working.
  team-utilisation-monitor/Microservice-Authentication/.gitignore
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: MicroServices

#263 🚧 (MicroServices)Added a third migration to micro
  team-utilisation-monitor/Microservice-Authentication/prisma/migrations/20220717184526_launch_3/migration.sql
Labels: database, MicroServices

#266 latest updated front-end, addition of explore page
  .idea/dictionaries/faresatheo.xml
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/comp-sidenav/comp-sidenav.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/ind-routing.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-explore-page/individual-explore-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
Labels: enhancement, front-end

#267 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#269 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-inidividual-stats.entity.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: api

#275 Develop
  team-utilisation-monitor/prisma/migrations/20220718191927_launch_20/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: database

#276 Gift
  team-utilisation-monitor/Microservice-Authentication/.dockerignore
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/AddSkill.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/AddSkill.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220718221308_launch_21/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, api

#278 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-skill.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetSkills.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetSkills.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: enhancement, backend, database, api

#279 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, database, api

#282 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.html
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/UpdateProfile.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/UpdateProfile.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end, backend, api

#284 🚧(front-end)- latest updates, add skills, auto scroll
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end, Done

#287 (MicroServices) VerifyToken is working in micro
  team-utilisation-monitor/Microservice-Authentication/dist/main.js
  team-utilisation-monitor/Microservice-Authentication/libs/auth-repository/src/auth-repository.service.ts
  team-utilisation-monitor/Microservice-Authentication/libs/auth-resolver/src/authentication-resolvers.resolver.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/queries/handlers/index.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/queries/handlers/verifyTokenHandler.handler.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/queries/impl/verifyToken.query.ts
  team-utilisation-monitor/Microservice-Authentication/libs/services/src/services.service.ts
  team-utilisation-monitor/Microservice-Authentication/prisma/schema.prisma
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: services, MicroServices

#286 Updated Add team member popup as well as added promote/demote button in Company View
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
Labels: front-end

#288 Develop
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#289 🚧 (Database) Added the migration for the new DB
  team-utilisation-monitor/prisma/migrations/20220720005048_launch_22/migration.sql
Labels: database

#290 🚧 (Frontend) Removed all of those pesky bottom texts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
Labels: front-end

#295 Develop
  team-utilisation-monitor/prisma/migrations/20220720015554_launch_23/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#296 🚧 (FrontEnd) SignUpAdmin was not hiding passwords
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.html
Labels: front-end

#297 Develop
  team-utilisation-monitor/prisma/migrations/20220720023912_launch_24/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#298 Develop
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#299 (Database) Removed the Active field from status
  team-utilisation-monitor/prisma/schema.prisma
Labels: database, api

#301 Develop
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/migrations/20220720035544_launch_26/migration.sql
  team-utilisation-monitor/prisma/migrations/20220720120612_launch_27/migration.sql
  team-utilisation-monitor/prisma/migrations/20220720120907_launch_28/migration.sql
  team-utilisation-monitor/prisma/migrations/20220720121533_launch_29/migration.sql
  team-utilisation-monitor/prisma/migrations/20220720123600_launch_29/migration.sql
  team-utilisation-monitor/prisma/migrations/20220720124632_launch_30/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#312 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as/signup-as.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/migrations/20220721132020_launch_31/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, database

#314 Made some Database fileds Nullable
  team-utilisation-monitor/prisma/migrations/20220721134455_launch_32/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#315 Develop
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#319 Gift
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/HistoricUtilization.entity.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end

#320 🚧 (Repository)Many-to-many:project-Teams working.
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/apps/api/src/app/app.module.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-data.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-project.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-project-to-team.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-project-to-team.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.controller.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220721141712_launch_33/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database, api, services

#321 🚧 (Services)Added AssignProjectToTeamsVName()
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-project-to-team-vname.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/asign-project-to-team-vname.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: api, services

#327 last updates of home page and profile before linking skills and moving on to explore
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
Labels: front-end, backend

#329 Gift
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/HistoricUtilization.entity.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend

#330 ✨ (UI):Delete Employee Working
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
Labels: front-end

#335 🚧 (Services)GetAllProjectsForATeamIsWorking
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-projects-of-teams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-projects-of-teams.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-teams-working-on-project.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, api

#338 🚧 (api) Added individual stats entity object
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-inidividual-stats.entity.ts
Labels: api

#339 Gift
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetUnderUtilizedEmployees.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetUnderUtilizedEmployees.query.ts
  team-utilisation-monitor/prisma/migrations/20220722150758_launch_34/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, api

#340 (api) Fixed the user-stats-entity
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-inidividual-stats.entity.ts
Labels: api

#341 updates
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/HistoricUtilization.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-inidividual-stats.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetUnderUtilizedEmployees.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-all-projects-of-teams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetUnderUtilizedEmployees.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-projects-of-teams.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/get-all-teams-working-on-project.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220722150758_launch_34/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: front-end, Done

#342 🐛 (UI):GetUtilizable Employees
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end

#343 ⚡️(front-end)-last and first name are no longer mandatory
  .vscode/settings.json
  team-utilisation-monitor/Microservice-Authentication/NX
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.scss
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end

#344 Develop
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-project.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end, api

#345 (Front-end)Fixed the linking.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
Labels: front-end, api

#347 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/prisma/migrations/20220723162357_launch_35/migration.sql
Labels: backend, api

#355 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/migrations/20220723190755_launch_36/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, database

#357 🩹 (Services) Fixes to the repository layer made
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend, Fix

#359 add hours input form and confirm button
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
Labels: front-end

#362 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-inidividual-stats.entity.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/UpdateProfile.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/UpdateUserSkill.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/UpdateProfile.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/UpdateUserSkill.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetAllocatedTeams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetUserSkills.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetUserStats.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/getAllocatedProjects.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetUserStats.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetUsersSkills.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/getAllocatedProjects.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/getAllocatedTeams.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api, services, repository

#366 Gift
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
Labels: front-end, backend, api

#367 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: front-end, database

#372 ⚡️ (UI):Linked current skills and individual stats
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end, backend, api

#373 update
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-inidividual-stats.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/UpdateProfile.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/UpdateUserSkill.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/UpdateProfile.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/UpdateUserSkill.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetAllocatedTeams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetUserSkills.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetUserStats.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/getAllocatedProjects.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetUserStats.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetUsersSkills.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/getAllocatedProjects.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/getAllocatedTeams.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220723190755_launch_36/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
  team-utilisation-monitor/prisma/seed.ts
Labels: backend

#375 ⚡️ (UI):Added Update User SKill service
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
Labels: front-end

#378 💄 (UI):Minor fix
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end

#379 minor updates
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: backend, database

#380 💄(front-end)-update user profile, update user skill
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end, backend, database, Done

#382 🚧(front-end)-profile skills list sep
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end, backend, database, api

#384 🚧(front-end)-nullCheckers removed
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: invalid, database

#386 no major changes, commits testing
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: wontfix

#387 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end, api

#388 🚑 Critical fix
  team-utilisation-monitor/.env
  team-utilisation-monitor/.gitignore
  team-utilisation-monitor/docker-compose.yml
Labels: Fix

#389 🚧 (Database) Modified the data access layer a bit
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: database

#391 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/AssignHours.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/CalculateUtilisation.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/AssignHours.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/CalculateUtilization.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, feature untested

#392 🚧 (services)Added functions folder for all our functions
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/functions.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/functions.service.spec.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/functions.service.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
Labels: front-end

#393 🚧 (Database) Added new migration 37
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/functions.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/functions.service.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.module.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220725155124_launch_37/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: backend, database

#395 Gift
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend

#397 🚧 (service)Utilisation running
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/NoneTerminalNode.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/TerminalNode.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/Tree.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/functions.service.ts
  team-utilisation-monitor/libs/service/feature/src/lib/functions/node.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/migrations/20220726074112_launch_38/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database, services

#398 🚧 (Servcies)Assigned weekly hours service is working.
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-weekly-hours.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-weekly-hours.command.ts
Labels: services

#399 🚧 (services)WeeklyHours is working
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/assign-weekly-hours.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-weekly-hours.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: api, services

#401 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/CalculateUtilisation.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetAvailableTeams.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetAvailableTeams.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, services

#402 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: fixed a bug, Fix

#404 Work on Graphs (more will be needed soon)
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end

#407 unit testing for loginComponent done
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.spec.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.spec.ts
  team-utilisation-monitor/libs/client/individual/NX
  team-utilisation-monitor/libs/client/individual/feature/src/lib/client-individual-feature.module.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/NX
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end, backend, database, api, Done

#406 Popop to show teams in project
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
Labels: front-end

#409 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
Labels: api

#410 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
Labels: front-end

#411 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end

#412 (Front-end)-Assign team to a project
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts
Labels: api

#416 Gift
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/HistoricUtilization.entity.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/utilization-graph/utilization-graph.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/weekly-utilisation-graph/weekly-utilisation-graph.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetMonthlyUtilization.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetMonthlyUtilization.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end

#422 (CI/CD) testing new workflow
  team-utilisation-monitor/apps/client-e2e/src/integration/app.spec.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
Labels: CI/CD

#423 update
  .github/workflows/node2.js.yml
  README.md
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/apps/client-e2e/src/integration/app.spec.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/HistoricUtilization.entity.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-skill.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.html
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/utilization-graph/utilization-graph.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/weekly-utilisation-graph/weekly-utilisation-graph.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetMonthlyUtilization.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/get-number-of-teams-of-company.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetMonthlyUtilization.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.spec.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: Done

#424 latest updates
  team-utilisation-monitor/.env
  team-utilisation-monitor/.gitignore
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.spec.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-home-page/individual-home-page.component.ts
Labels: front-end, backend, Done

#425 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/index.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/CompanyUtilization.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetCompanyUtilization.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetCompanyUtilization.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api

#427 Gift
  team-utilisation-monitor/.env
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-team.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-graph-company-utilization/comp-graph-company-utilization.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/CompleteProject.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/DeleteProject.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/CompleteProject.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/DeleteProject.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/GetTeamsOnProject.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/queries/impl/GetTeamsOnProject.query.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: front-end, api

#430 (Final) Final touches
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.spec.ts
Labels: test, Testing

#432 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-individual/comp-team-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-individual/comp-team-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: backend, api

#434 Bug Fix: List View not displaying Util Chart
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
Labels: front-end, fixed a bug

#438 Bug fix: added more cases to List View bar chart
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
Labels: front-end, fixed a bug

#439 Gift
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-list-view/admin-list-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-list-view-individual/comp-list-view-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: front-end

#442 Gift
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-company-stats.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: bug, backend, fixed a bug, Fix

#440 Develop
  team-utilisation-monitor/apps/client-e2e/src/integration/app.spec.ts
  team-utilisation-monitor/apps/client-e2e/src/integration/queries.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
Labels: test, Testing
