Repository COS301-SE-2022/Team-Utilisation-Monitor, pull requests merged in 2022-10, with the labels that each got.

#645 (Fix) admin company view was giving errors
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
Labels: front-end, Fix

#646 (Fix) Fixed the assign hours.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
Labels: front-end, Fix

#648 Front end UI Updates
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
Labels: front-end

#649 Develop
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
Labels: Fix

#650 Gift
  team-utilisation-monitor/docker-compose.yml
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: bug, backend, api

#652 (FrontEnd) Removed an alert on comp-employee-individual.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
Labels: front-end

#653 (FrontEnd) Remove team is working on ngxs
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
Labels: front-end

#655 🐛 (Fix)Team/project view addProject
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: front-end, NGSX

#656 🎨 (FaceLift) Added MatSnacks to the individual page
  team-utilisation-monitor/libs/client/individual/feature/src/lib/individual-profile/individual-profile.component.ts
Labels: front-end
