Repository COS301-SE-2022/Team-Utilisation-Monitor, pull requests merged in 2022-08, with the labels that each got.

#443 (services) Done something.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
Labels: services

#445 💚 (CI/CD) added the working directory
  .github/workflows/node3.js.yml
  team-utilisation-monitor/apps/client/src/app/app.component.spec.ts
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/apps/client/tsconfig.json
Labels: api, CI/CD

#446 (CI/CD) Fix #4. Removed intergration tests to the api
  .github/workflows/node3.js.yml
  team-utilisation-monitor/apps/client-e2e/src/integration/app.spec.ts
Labels: CI/CD

#455 🚧 (Repository) Added Null Exceptions to the data repository layer
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/libs/repository/data-access/src/index.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/index.ts
  team-utilisation-monitor/libs/shared/services/prisma-services/src/lib/Exceptions/NullException.ts
Labels: repository

#456 (Front) Added some alerts to give more clarity
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-company/signup-as-company.component.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/signup-as-individual/signup-as-individual.component.ts
Labels: front-end

#458 🚧 (database)Added the active_Token field to person DB
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/individual/feature/src/index.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/prisma/migrations/20220806014414_launch_39/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#459 🚧 (services) setToken function created
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/set-token.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/set-token.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: services

#460 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/index.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/verify-token.handler.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/verify-token.command.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
Labels: database, services

#461 (Fix) The login functionality wasn't working
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: api, services

#462 🚧 (services) SetActiveToken() is working
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/verify-token.handler.ts
Labels: api, services

#463 🚧 (api)getOnePerson() is tokenised
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: api

#464 🚧 (api)All individual functions are tokenised
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
Labels: api

#466 Gift
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/Individual.service.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/verify-token.handler.ts
Labels: backend

#467 Develop
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/Authentication.service.ts
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
Labels: api, Fix

#469 Microservices bug fix:Ran migration launch_4
  team-utilisation-monitor/Microservice-Authentication/prisma/migrations/20220809180233_launch_4/migration.sql
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: MicroServices

#472 Add tooltips to Admin Pages
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-data-view-popup/comp-project-data-view-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-individual/comp-team-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
Labels: front-end

#473 Gift
  team-utilisation-monitor/libs/api/shared/data-access/src/lib/api-user-person.entity.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-company-view/admin-company-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/impl/assign-weekly-hours.command.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: front-end, backend

#474 🚧 (services) Asigned token function to handler instead of repository.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/service/feature/src/lib/commands/handlers/verify-token.handler.ts
Labels: services, fixed a bug, Fix

#476 (Services) Admin functions tokenised
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
Labels: services

#478 🐛 (Fix)Fixed the pending request problem.
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
Labels: Fix

#479 Gift
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
  team-utilisation-monitor/libs/service/feature/src/lib/service-feature.service.ts
  team-utilisation-monitor/prisma/schema.prisma
Labels: services

#480 🚧 (NGXS)Our Add members to company is working.
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-employees.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-nav-request-users/comp-nav-request-users.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-number-of-employees.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-employees.state.ts
  team-utilisation-monitor/libs/client/admin/feature/tsconfig.json
  team-utilisation-monitor/package.json
  team-utilisation-monitor/yarn.lock
Labels: front-end, NGSX

#481 🐛 (CI/CD) Fixed a ci/cd error.
  team-utilisation-monitor/apps/client/project.json
Labels: Fix, CI/CD

#482 (NGXS) Ngxs files added
  team-utilisation-monitor/libs/client/admin/feature/src/lib/Admin.service.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-teams.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-number-of-projects.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-number-of-teams.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-projects.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-teams.state.ts
Labels: NGSX

#483 🚧 (NGXS)Defined the actions and states
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-employees.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-teams.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-number-of-projects.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-number-of-teams.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-employees.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-projects.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-teams.state.ts
Labels: NGSX

#485 Added proper angular Popups for All admin Pages
  team-utilisation-monitor/libs/client/admin/feature/src/lib/client-admin-feature.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-user-popup/comp-add-user-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-individual/comp-team-individual.component.ts
Labels: front-end, fixed a bug

#487 Gift
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: fixed a bug, repository

#489 Theo sprint4
  team-utilisation-monitor/libs/client/individual/feature/src/lib/actions/number-of-projects.actions.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/actions/number-of-skills.actions.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/actions/number-of-teams.actions.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/actions/skill.actions.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/models/number-of-projects.model.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/models/number-of-skills.model.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/models/number-of-teams.model.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/models/skill.model.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/state/number-of-projects.state.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/state/number-of-skills-state.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/state/number-of-teams.state.ts
  team-utilisation-monitor/libs/client/individual/feature/src/lib/state/skill.state.ts
Labels: in progress, NGSX

#494 Develop
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-employees.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-number-of-teams.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-home-page/admin-home-page.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-employees.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-projects.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-teams.state.ts
Labels: front-end, backend, NGSX

#495 (Ngxs)Setup ngxs for team-project-view
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-team.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-member-popup/comp-add-team-member-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-project.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-team.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/project.stat.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/teams.state.ts
Labels: NGSX

#496 (ngsx)Team/project view working when create project.
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-add-team.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-project-popup/comp-create-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/number-of-employees.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/project.stat.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/project.state.ts
Labels: NGSX

#497 (ngsx)Adding teams using ngxs created!
  team-utilisation-monitor/apps/client/src/app/app.module.ts
  team-utilisation-monitor/libs/client/admin/feature/src/index.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-team-to-project-popup/comp-add-team-to-project-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-individual/comp-team-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/models/admin-team.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/project.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/team.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/teams.state.ts
Labels: NGSX

#499 🚧 (Database)Added launch_40
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.ts
  team-utilisation-monitor/prisma/migrations/20220822170327_launch_40/migration.sql
  team-utilisation-monitor/prisma/schema.prisma
Labels: database

#501 🚧 (ngsx) Delete working for Projects- Team/Project view
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-project.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/project.state.ts
Labels: NGSX

#506 🚧 (ngxs) Added alerts to updateWeeklyHours
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-employee-individual/comp-employee-individual.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.ts
Labels: front-end

#507 Develop
  team-utilisation-monitor/apps/api/src/app/app.controller.ts
  team-utilisation-monitor/libs/api/feature/src/lib/api-feature/api-feature.resolver.ts
Labels: api, Fix

#508 Gift
  team-utilisation-monitor/libs/repository/data-access/src/lib/data-access.repository.ts
Labels: backend

#509 🚧(ngxs)addskills angular bounded
  team-utilisation-monitor/libs/client/admin/feature/src/lib/admin-team-project-view/admin-team-project-view.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.ts
  team-utilisation-monitor/prisma/seed.ts
Labels: front-end, NGSX

#510 (FIX)ngxs team/project view is fixed
  team-utilisation-monitor/libs/client/admin/feature/src/lib/actions/mutate-remove-team.action.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-create-team-popup/comp-create-team-popup.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/project.state.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/states/team.state.ts
Labels: fixed a bug, Fix

#513 Update Team/Project View on Admin Pages
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-add-skills-popup/comp-add-skills-popup.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-navbar/comp-navbar.component.ts
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-project-list/comp-project-list.component.scss
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.html
  team-utilisation-monitor/libs/client/admin/feature/src/lib/comp-team-list/comp-team-list.component.scss
  team-utilisation-monitor/libs/client/authentication/feature/src/lib/login/login.component.scss
Labels: front-end
